In [3]:
import sys
import numpy as np

In [4]:
array_ld = np.array([4.5, 3])
type(array_ld)

numpy.ndarray

In [5]:
array_ld.ndim

1

In [6]:
array_ld.shape

(2,)

In [7]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
matriz.ndim

2

In [9]:
matriz.shape

(2, 3)

In [10]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((2))

array([1., 1.])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random((2, 3))

array([[0.34991504, 0.14372831, 0.49202581],
       [0.44254925, 0.45111303, 0.28989723]])

In [ ]:
!copy con np_text.txt

In [ ]:
np_text = np.genfromtxt("np_text.txt", delimiter = '.')
np_text

In [1]:
lista_2d = [[1, 2, 3], [4, 5, 6]]
lista_2d

[[1, 2, 3], [4, 5, 6]]

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
sys.getsizeof(lista_2d)

80

In [6]:
sys.getsizeof(array_2d)

136

In [7]:
big_lista = list(range(1000000))
big_array = np.array(range(1000000))

In [10]:
sys.getsizeof(big_lista)

9000112

In [11]:
sys.getsizeof(big_array)

4000096

In [16]:
%%timeit
sum(range(1000000))

38.6 ms ± 215 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
%%timeit
np.sum(np.arange(1000000))

2.63 ms ± 32.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
np.array([1.0, 5.4], dtype = int).dtype

dtype('int32')

In [20]:
np.array([1.0, 2.0, "patatas"])

array(['1.0', '2.0', 'patatas'], dtype='<U32')

In [21]:
%%timeit
["{}".format(i) for i in range(100000)]

27.4 ms ± 477 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
f = np.vectorize(lambda x: "{}".format(x))

In [23]:
%%timeit
f(np.arange(100000))

52.5 ms ± 5.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [24]:
matriz_34 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
matriz_34[0]

array([1, 2, 3, 4])

In [26]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
matriz_34[:, 1]

array([ 2,  6, 10])

In [29]:
matriz_34[1][1]

6

In [30]:
seleccion = matriz_34[1, 3]
print(seleccion)
seleccion = 100
matriz_34

8


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
seccion = matriz_34[:2]
seccion


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
seccion[0, 0] = 100
matriz_34

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [35]:
matriz_32 = np.array([
    [1, 4],
    [2, 4],
    [5, 0]
])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [37]:
indice_filtrado = matriz_32 >= 2
indice_filtrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [39]:
matriz_32[indice_filtrado]

array([4, 2, 4, 5])

In [40]:
array1 = np.array([[1, 2], [3, 4]])

In [41]:
array2 = np.array([[23, 51], [3, 0]])

In [42]:
array1 + array2

array([[24, 53],
       [ 6,  4]])

In [43]:
array1 * array2

array([[ 23, 102],
       [  9,   0]])

In [44]:
array1 @ array2

array([[ 29,  51],
       [ 81, 153]])

In [45]:
array1.dot(array2)

array([[ 29,  51],
       [ 81, 153]])