In [6]:
import numpy as np

In [10]:
array = np.array([[1, 6, 11], 
                  [2, 7, 12], 
                  [3, 8, 13], 
                  [4, 9, 14], 
                  [5, 10, 15]])

In [11]:
type(array)

numpy.ndarray

In [12]:
array.shape

(5, 3)

In [63]:
array.ndim

2

In [69]:
array[:, 1]

array([ 6,  7,  8,  9, 10])

In [70]:
array2_1 = np.arange(15, 56)
array2_1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [84]:
array2_1[1::2]

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48,
       50, 52, 54])

In [85]:
array2_1[1::2][:5]

array([16, 18, 20, 22, 24])

In [71]:
array2_1[4] = 23
array2_1

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [72]:
array_reverse = []
for i in range(1, len(array2_1)):
    array_reverse.append(array2_1[-i])

print(array_reverse)

[55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 23, 18, 17, 16]


In [73]:
array2_1[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [103]:
matriz_diag = np.diag(array2_1[:5])
matriz_diag

array([[15,  0,  0,  0,  0],
       [ 0, 16,  0,  0,  0],
       [ 0,  0, 17,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 23]])

In [104]:
other = np.diag(array_reverse[1::2][:5])
other

array([[54,  0,  0,  0,  0],
       [ 0, 52,  0,  0,  0],
       [ 0,  0, 50,  0,  0],
       [ 0,  0,  0, 48,  0],
       [ 0,  0,  0,  0, 46]])

In [89]:
other.ndim

2

In [105]:
matriz_diag.shape

(5, 5)

In [102]:
matriz = np.random.random((5, 3))
matriz

array([[0.41538196, 0.15885964, 0.84550795],
       [0.40922131, 0.6492938 , 0.5989198 ],
       [0.05902351, 0.58870252, 0.48882518],
       [0.79335539, 0.86775681, 0.94459741],
       [0.44087208, 0.31665695, 0.11151596]])

In [106]:
matriz.shape

(5, 3)

In [107]:
matriz_diag.shape

(5, 5)

In [109]:
mult = matriz_diag @ matriz
mult

array([[ 6.2307294 ,  2.38289455, 12.6826193 ],
       [ 6.54754092, 10.38870082,  9.58271675],
       [ 1.00339965, 10.00794291,  8.31002799],
       [14.2803971 , 15.61962256, 17.0027534 ],
       [10.14005789,  7.28310974,  2.56486715]])

In [111]:
mult = matriz.T @ matriz_diag
mult

array([[ 6.2307294 ,  6.54754092,  1.00339965, 14.2803971 , 10.14005789],
       [ 2.38289455, 10.38870082, 10.00794291, 15.61962256,  7.28310974],
       [12.6826193 ,  9.58271675,  8.31002799, 17.0027534 ,  2.56486715]])