### Regularización en Keras

In [1]:
%load_ext watermark
%watermark

2019-04-10T01:51:47-05:00

CPython 3.7.3rc1
IPython 7.3.0

compiler   : MSC v.1916 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
CPU cores  : 4
interpreter: 64bit


In [3]:
from IPython.display import Image


import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10, 8)

# Cargamos los datos

En deep learning no se suele hacer validación cruzada (a menos que el tamaño del dataset y el tiempo de entrenamiento lo permita). En lugar de eso se hacen simples separaciónes entre datos de entrenamiento y de validación.

In [4]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 10s 1us/step


In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_train[0].shape

(28, 28)

In [7]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
from ipywidgets import interact, IntSlider

In [9]:
@interact(i = IntSlider(min = 0,max = 50,step = 1,value = 1))
def dibujar_numero(i):
    plt.imshow(x_train[i], cmap = "gray")
    plt.title("Número {}".format(y_train[i]))

interactive(children=(IntSlider(value=1, description='i', max=50), Output()), _dom_classes=('widget-interact',…

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten

In [11]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [12]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [13]:
x_train[0].shape

(28, 28)

In [17]:
x_train_plano = x_train.reshape(x_train.shape[0], 28 * 28)
x_test_plano = x_test.reshape(x_test.shape[0], 28 * 28)

In [18]:
x_train_plano[0].shape

(784,)

In [19]:
x_train_plano[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [20]:
from keras.utils.np_utils import to_categorical

In [21]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [22]:
y_train_one_hot = to_categorical(y_train)
y_test_one_hot = to_categorical(y_test)

In [23]:
y_train_one_hot[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [33]:
modelo = Sequential()
modelo.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo.add(Dense(250, activation = "relu"))
modelo.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_5 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [34]:
modelo.fit(x_train_plano, y_train_one_hot, epochs = 50, batch_size = 1000, verbose = 1); #batch_size = 1000 original

Epoch 1/50
60000/60000 [==============================] - 1s 16us/step - loss: 8.4553 - acc: 0.4281
Epoch 2/50
60000/60000 [==============================] - 1s 14us/step - loss: 1.1064 - acc: 0.8248
Epoch 3/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.6787 - acc: 0.8627
Epoch 4/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.5355 - acc: 0.8832
Epoch 5/50
60000/60000 [==============================] - 1s 13us/step - loss: 0.4555 - acc: 0.8971
Epoch 6/50
60000/60000 [==============================] - 1s 13us/step - loss: 0.4001 - acc: 0.9061
Epoch 7/50
60000/60000 [==============================] - 1s 13us/step - loss: 0.3587 - acc: 0.9146
Epoch 8/50
60000/60000 [==============================] - 1s 13us/step - loss: 0.3302 - acc: 0.9190
Epoch 9/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.3038 - acc: 0.9252
Epoch 10/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.2812 - acc: 0.9291

Vamos a ver ahora como se compara el funcionamiento del modelo respecto a los datos de entrenamiento y los de test. 

In [35]:
RESULTADOS = {}

In [36]:
modelo.metrics_names

['loss', 'acc']

In [37]:
evaluacion_train = modelo.evaluate(x_train_plano, y_train_one_hot)
evaluacion_train

60000/60000 [==============================] - 1s 24us/step


[0.0801267801308694, 0.9783833333333334]

In [38]:
evaluacion_test = modelo.evaluate(x_test_plano, y_test_one_hot)
evaluacion_test

10000/10000 [==============================] - 0s 27us/step


[0.2800670197776053, 0.9417]

In [39]:
RESULTADOS["sin_regularizacion"] = [evaluacion_train[1], evaluacion_test[1]]

### Regularización l1, o l2

Keras permite regularizar los pesos, los sesgos (bias) y las activaciones de  forma independiente, pasando el parámetro `kernel_regularizer`, `bias_regularizer` y `activity_regularizer` respectivamente.

Keras tiene los penalizadores `l1`, `l2` y `l1_l2` (elasticnet)

In [40]:
from keras import regularizers

modelo_l2 = Sequential()
modelo_l2.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo_l2.add(Dense(250, activation = "relu", kernel_regularizer = regularizers.l2(0.01)))
modelo_l2.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo_l2.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo_l2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 50)                39250     
_________________________________________________________________
dense_8 (Dense)              (None, 250)               12750     
_________________________________________________________________
dense_9 (Dense)              (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


In [41]:
modelo_l2.fit(x_train_plano, y_train_one_hot, verbose = 1, epochs = 50, batch_size = 1000);

Epoch 1/50
60000/60000 [==============================] - 1s 17us/step - loss: 10.9345 - acc: 0.3559
Epoch 2/50
60000/60000 [==============================] - 1s 14us/step - loss: 4.0106 - acc: 0.7301
Epoch 3/50
60000/60000 [==============================] - 1s 13us/step - loss: 1.5326 - acc: 0.8653
Epoch 4/50
60000/60000 [==============================] - 1s 13us/step - loss: 1.2942 - acc: 0.8917
Epoch 5/50
60000/60000 [==============================] - 1s 13us/step - loss: 1.1836 - acc: 0.9034
Epoch 6/50
60000/60000 [==============================] - 1s 15us/step - loss: 1.0984 - acc: 0.9127
Epoch 7/50
60000/60000 [==============================] - 1s 14us/step - loss: 1.0332 - acc: 0.9214
Epoch 8/50
60000/60000 [==============================] - 1s 15us/step - loss: 0.9828 - acc: 0.9265
Epoch 9/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.9396 - acc: 0.9311
Epoch 10/50
60000/60000 [==============================] - 1s 14us/step - loss: 0.9039 - acc: 0.934

In [42]:
acc_train = modelo_l2.evaluate(x_train_plano, y_train_one_hot)[1]
acc_train

60000/60000 [==============================] - 2s 25us/step


0.9838333333333333

In [43]:
acc_test = modelo.evaluate(x_test_plano, y_test_one_hot)[1]
acc_test

10000/10000 [==============================] - 0s 27us/step


0.9417

In [44]:
RESULTADOS["regularizacion_l2"] = [acc_train, acc_test]

Hacemos lo mismo pero con regularización l1

In [45]:
modelo_l1 = Sequential()
modelo_l1.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo_l1.add(Dense(250, activation = "relu", kernel_regularizer = regularizers.l1(0.01)))
modelo_l1.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo_l1.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo_l1.fit(x_train_plano, y_train_one_hot, verbose = 1, epochs = 50, batch_size = 1000)

acc_train = modelo_l1.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_l1.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["regularizacion_l1"] = [acc_train, acc_test]

Epoch 1/50
60000/60000 [==============================] - 1s 17us/step - loss: 14.2270 - acc: 0.5873
Epoch 2/50
60000/60000 [==============================] - 1s 13us/step - loss: 8.5482 - acc: 0.8336
Epoch 3/50
60000/60000 [==============================] - 1s 13us/step - loss: 7.5514 - acc: 0.8665
Epoch 4/50
60000/60000 [==============================] - 1s 13us/step - loss: 6.7882 - acc: 0.8846
Epoch 5/50
60000/60000 [==============================] - 1s 13us/step - loss: 6.0856 - acc: 0.8990
Epoch 6/50
60000/60000 [==============================] - 1s 15us/step - loss: 5.4459 - acc: 0.9081
Epoch 7/50
60000/60000 [==============================] - 1s 16us/step - loss: 4.8496 - acc: 0.9169
Epoch 8/50
60000/60000 [==============================] - 1s 15us/step - loss: 4.2972 - acc: 0.9220
Epoch 9/50
60000/60000 [==============================] - 1s 14us/step - loss: 3.7767 - acc: 0.9281
Epoch 10/50
60000/60000 [==============================] - 1s 14us/step - loss: 3.3088 - acc: 0.928

In [46]:
print(acc_train, acc_test)

0.96335 0.9545


### Dropout

Ahora vamos a añadir Dropout a la misma red. Dropout simplemente ignora un porcentaje `p` de las unidades (neuronas) en cada iteración del entrenamiento (forward prop y backprop)

In [47]:
from keras.layers import Dropout

In [48]:
modelo_dropout = Sequential()
modelo_dropout.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo_dropout.add(Dense(250, activation = "relu"))
modelo_dropout.add(Dropout(0.2))
modelo_dropout.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo_dropout.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo_dropout.summary()

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_14 (Dense)             (None, 250)               12750     
_________________________________________________________________
dropout_1 (Dropout)          (None, 250)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 10)                2510      
Total params: 54,510
Trainable params: 54,510
Non-trainable params: 0
_________________________________________________________________


Vemos que el número de parámetros a entrenar es el mismo, Dropout no añade pesos a la red

In [49]:
modelo_dropout.fit(x_train_plano, y_train_one_hot, verbose = 1, epochs = 50, batch_size = 1000);

Epoch 1/50
60000/60000 [==============================] - 2s 25us/step - loss: 7.5411 - acc: 0.5010
Epoch 2/50
60000/60000 [==============================] - 1s 18us/step - loss: 3.2666 - acc: 0.7638
Epoch 3/50
60000/60000 [==============================] - 1s 18us/step - loss: 2.6547 - acc: 0.8051
Epoch 4/50
60000/60000 [==============================] - 1s 19us/step - loss: 1.1506 - acc: 0.8927
Epoch 5/50
60000/60000 [==============================] - 1s 18us/step - loss: 0.8863 - acc: 0.9066
Epoch 6/50
60000/60000 [==============================] - 1s 18us/step - loss: 0.7337 - acc: 0.9110: 0s - loss: 0.7338
Epoch 7/50
60000/60000 [==============================] - 1s 20us/step - loss: 0.6402 - acc: 0.9137
Epoch 8/50
60000/60000 [==============================] - 1s 19us/step - loss: 0.5561 - acc: 0.9188
Epoch 9/50
60000/60000 [==============================] - 1s 23us/step - loss: 0.4931 - acc: 0.9233
Epoch 10/50
60000/60000 [==============================] - 1s 21us/step - loss: 0

In [50]:
acc_train = modelo_dropout.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_dropout.evaluate(x_test_plano, y_test_one_hot)[1]

10000/10000 [==============================] - 0s 28us/step


In [51]:
print(acc_train, acc_test)

0.9781166666666666 0.9541


In [53]:
RESULTADOS["regularizacion_dropout"] = [acc_train, acc_test]

### Normalización en bloques (batch normalization)

In [54]:
from keras.layers import BatchNormalization

In [55]:
modelo_bnorm = Sequential()
modelo_bnorm.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo_bnorm.add(Dense(250, activation = "relu"))
modelo_bnorm.add(BatchNormalization())
modelo_bnorm.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo_bnorm.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo_bnorm.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 50)                39250     
_________________________________________________________________
dense_17 (Dense)             (None, 250)               12750     
_________________________________________________________________
batch_normalization_1 (Batch (None, 250)               1000      
_________________________________________________________________
dense_18 (Dense)             (None, 10)                2510      
Total params: 55,510
Trainable params: 55,010
Non-trainable params: 500
_________________________________________________________________


In [56]:
modelo_bnorm.fit(x_train_plano, y_train_one_hot, verbose = 1, epochs = 50, batch_size = 1000)
acc_train = modelo_bnorm.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization"] = [acc_train, acc_test]
print(acc_train, acc_test)

Epoch 1/50
60000/60000 [==============================] - 2s 30us/step - loss: 1.2156 - acc: 0.6270
Epoch 2/50
60000/60000 [==============================] - 1s 20us/step - loss: 0.6069 - acc: 0.8244
Epoch 3/50
60000/60000 [==============================] - 1s 22us/step - loss: 0.4729 - acc: 0.8645
Epoch 4/50
60000/60000 [==============================] - 1s 20us/step - loss: 0.4046 - acc: 0.8848
Epoch 5/50
60000/60000 [==============================] - 1s 25us/step - loss: 0.3618 - acc: 0.8976
Epoch 6/50
60000/60000 [==============================] - 1s 20us/step - loss: 0.3312 - acc: 0.9064
Epoch 7/50
60000/60000 [==============================] - 1s 20us/step - loss: 0.3085 - acc: 0.9128
Epoch 8/50
60000/60000 [==============================] - 1s 19us/step - loss: 0.2904 - acc: 0.9177
Epoch 9/50
60000/60000 [==============================] - 1s 18us/step - loss: 0.2756 - acc: 0.9212
Epoch 10/50
60000/60000 [==============================] - 1s 18us/step - loss: 0.2632 - acc: 0.9258

### Batch Normalization + Dropout

Una práctica común es poner normalizacion batch y dropout juntos en una capa

In [57]:
modelo_bnorm_drop = Sequential()
modelo_bnorm_drop.add(Dense(50, activation = "relu", input_shape = (784,)))
modelo_bnorm_drop.add(Dense(250, activation = "relu"))
modelo_bnorm_drop.add(BatchNormalization())
modelo_bnorm_drop.add(Dropout(0.2))
modelo_bnorm_drop.add(Dense(np.unique(y_train).shape[0], activation = "softmax"))

modelo_bnorm_drop.compile(optimizer = "sgd", loss = "categorical_crossentropy", 
               metrics = ["accuracy"])

modelo_bnorm_drop.fit(x_train_plano, y_train_one_hot, verbose = 0, epochs = 50, batch_size = 1000)
acc_train = modelo_bnorm_drop.evaluate(x_train_plano, y_train_one_hot)[1]
acc_test = modelo_bnorm_drop.evaluate(x_test_plano, y_test_one_hot)[1]

RESULTADOS["batch_normalization + dropout"] = [acc_train, acc_test]
print(acc_train, acc_test)

10000/10000 [==============================] - 0s 33us/step
0.9648 0.9569


Ahora metemos los resultados en un dataframe para inspeccionarlos

In [58]:
import pandas as pd

resultados = pd.DataFrame(RESULTADOS).T
resultados.columns = ["acc_train", "acc_test"]
resultados["pct_diff"] = 1 - (resultados.acc_test / resultados.acc_train)

In [60]:
resultados.sort_values(by = "pct_diff")

acc_train  acc_test  pct_diff
batch_normalization + dropout   0.964800    0.9569  0.008188
regularizacion_l1               0.963350    0.9545  0.009187
batch_normalization             0.967133    0.9581  0.009340
regularizacion_dropout          0.978117    0.9541  0.024554
sin_regularizacion              0.978383    0.9417  0.037494
regularizacion_l2               0.983833    0.9417  0.042826